---
EnableDefaultLinters: true
exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'public/**/*'
  - 'storage/**/*'
  - 'tmp/**/*'
  - 'log/**/*'
  - 'coverage/**/*'
  - 'spec/**/*'
  - 'test/**/*'
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
  AllowedScriptType:
    enabled: true
    allowed_types:
      - text/javascript
      - application/javascript
  ClosingErbTagIndent:
    enabled: true
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  ParserErrors:
    enabled: true
  RequireInputAutocomplete:
    enabled: true
  RightTrim:
    enabled: true
  SelfClosingTag:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  CommentSyntax:
    enabled: true
