# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Exclude third-party gems and local gem development
AllCops:
  Exclude:
    - 'pay/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
